name: rotmg_utility
description: An utility tool for Realm of the Mad God.
publish_to: 'none' # Remove this line if you wish to publish to pub.dev
version: 1.2.0

environment:
  sdk: ">=2.7.0 <3.0.0"

dependencies:
  flutter:
    sdk: flutter
  web_scraper: ^0.0.0
  time_formatter: ^1.0.0
  hive: ^1.4.4
  hive_flutter: ^0.3.1
  path_provider: ^1.6.14
  path_provider_windows: ^0.0.1+2

dev_dependencies:
  flutter_test:
    sdk: flutter
  hive_generator: ^0.7.1
  build_runner: ^1.10.2

flutter:
  uses-material-design: true
  assets:
    - images/
    - images/armor/
    - images/weapons/
    - images/pots/
    - images/eggs/
    - images/class/
    - images/rings/
    - images/chars/
    - images/stars/
    - images/quests/craft/
    - images/quests/beginner/
    - images/quests/epic/
    - images/quests/mighty/
    - images/quests/rewards/
    - images/quests/standart/
    - assets/backgrounds/
    - assets/

  fonts:
    - family: PS2P
      fonts:
        - asset: fonts/PressStart2P-Regular.ttf

